name: ci-test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U root -d simple_bank"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install migrate CLI
        run: |
          curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | gpg --dearmor > migrate-keyring.gpg
          sudo install -o root -g root -m 644 migrate-keyring.gpg /usr/share/keyrings/migrate-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/migrate-keyring.gpg] https://packagecloud.io/golang-migrate/migrate/ubuntu/ jammy main" | sudo tee /etc/apt/sources.list.d/migrate.list
          sudo apt-get update
          sudo apt-get install -y migrate

      - name: Run migrations
        run: make migrateup

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
